"""add column rf-token

Revision ID: 39d22b63dda0
Revises: 6434c9bc2198
Create Date: 2026-04-22 18:31:16.009093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39d22b63dda0'
down_revision: Union[str, Sequence[str], None] = '6434c9bc2198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('rf_token', sa.String(length=1024), nullable=False))
    op.create_unique_constraint(None, 'refresh_tokens', ['rf_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_column('refresh_tokens', 'rf_token')
    # ### end Alembic commands ###
